// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAHjDynzjTSqqZsSoHWqfa_ThyasODn9s',
    appId: '1:350745739273:web:d1145d809144c40facf8d8',
    messagingSenderId: '350745739273',
    projectId: 'baustaka',
    authDomain: 'baustaka.firebaseapp.com',
    storageBucket: 'baustaka.appspot.com',
    measurementId: 'G-5CP66XB8SK',
  );

  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyC4EZVUbOyLSSn5etZ9vhyNjrublcRHJtE',
  //   appId: '1:350745739273:android:dad59c5b5fecb6feacf8d8',
  //   messagingSenderId: '350745739273',
  //   projectId: 'baustaka',
  //   storageBucket: 'baustaka.appspot.com',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy6ZwooIR1pIqoMzNu5WaiD_m1FJnzoXw',
    appId: '1:190957972509:android:a9887ae49a03f7ca9aaaf4',
    messagingSenderId: '190957972509',
    projectId: 'baus-test-83bcc',
    storageBucket: 'baus-test-83bcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmSwRINnSmdz9c6dBvFQdFb6GxSDQ76v4',
    appId: '1:350745739273:ios:0c2c4dc616c29b9bacf8d8',
    messagingSenderId: '350745739273',
    projectId: 'baustaka',
    storageBucket: 'baustaka.appspot.com',
    androidClientId: '350745739273-21bdod8po35ti6l8fgmd5h1vdm9uf4nq.apps.googleusercontent.com',
    iosClientId: '350745739273-d64i94n7rpunrtlaelc7kudtdm3dp074.apps.googleusercontent.com',
    iosBundleId: 'ke.co.baustaka.client',
  );
}
